// <auto-generated />
namespace Doctor.Con.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReviews));
        
        string IMigrationMetadata.Id
        {
            get { return "202405301548198_AddReviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
