// <auto-generated />
namespace Doctor.Con.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDoctors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDoctors));
        
        string IMigrationMetadata.Id
        {
            get { return "202405231333213_AddDoctors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
